; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_deps =
    arduino-libraries/Servo
build_flags =
    -I ./include/actuators/motors/h_bridges
    -I ./include/actuators/motors
    -I ./include/actuators/motors/servo
    -I ./include/actuators/motors/h_bridges/l293d
    -I ./include/actuators/motors/h_bridges/bts7960
    -I ./include/actuators/motors/h_bridges/tb6612fng
    -I ./include/actuators/sound/buzzer
    -I ./include/actuators/leds/rgb
    -I ./include/actuators/leds/monocolor
    -I ./include/sensors/ultrasonic
    -I ./include/sensors/humidity
    -I ./include/sensors/speed
